service: svg_to_pdf

image: o201/svg_to_pdf

# Deploy to these servers.
servers:
  web:
    - 91.199.32.203
proxy:
  ssl: true
  host: ns1.126399.ip-ns.net

registry:
  username: o201
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    SOLID_QUEUE_IN_PUMA: true

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "svg_to_pdf_storage:/rails/storage"

asset_path: /rails/public/assets
builder:
  arch: amd64
